Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 50

Metrics/BlockLength:
  Max: 50

Style/Documentation:
  Enabled: false

Style/RegexpLiteral:
  EnforcedStyle: slashes
  AllowInnerSlashes: true

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Metrics/BlockLength:
  Exclude:
    - ./spec/**/*

Metrics/AbcSize:
  Enabled: false
